### ISSUE TITLE
types file is not a module.

### ISSUE THREAD

**Issue by AdrienLemaire** [esamattis/postcss-ts-classnames#2]
Please add an option to generate a module.

In that case, the generated output would be:
```diff
- type ClassNames = "button" | "button-danger";
+ export type ClassNames = "button" | "button-danger";
```

For context, that would enable me to use it as custom types file with [tailwindcss-classnames](https://github.com/muhammadsammy/tailwindcss-classnames#cli-arguments-for-tailwind-config).

**Comment by esamattis** [comment]
PR welcome!

**Comment by AdrienLemaire** [comment]
@esamattis it would be great if the PR could be merged soon and npm package bumped, I do not seem able to use my github fork as dependency due to lack of dist files.

**Comment by esamattis** [comment]
Ah missed that. v0.2.0 is out now! 🎉
