### ISSUE TITLE
Human readable formatting for output

### ISSUE THREAD

**Issue by aivenkimmob** [esamattis/postcss-ts-classnames#4]
Hello, thanks for the great library.

This is a feature request, would it be possible to add a flag for human readable output? I'm now running `sed -i 's/" |/"\n  |/g' types/tailwindGenerated.d.ts` to make output look like this:

```ts
export type ClassNames = "-bottom-1"
  | "-bottom-1\/2"
  | "-bottom-1\/3"
  | "-bottom-1\/4"
  | "-bottom-1px"
  | "-bottom-2"
  | "-bottom-2\/3"
  // ... ~40 000 lines..
  | "z-auto";
```

Would you be willing to accept a PR that implements this feature and what should the option be named?

**Comment by esamattis** [comment]
Thanks!

PR is welcome for sure. I don't think this needs an option. I think it would be the best just to make the generation prettier by default in `getTypeScriptType`:

https://github.com/esamattis/postcss-ts-classnames/blob/991868ea4553fdcec5d4c361a023cb44892c9c87/src/class-name-collector.ts#L63-L68
