### ISSUE TITLE
export default

### ISSUE THREAD

**Issue by AdrienLemaire** [esamattis/postcss-ts-classnames#7]
Can we export default when setting isModule to true ?

```diff
export type ClassNames =
   ...
export default ClassNames;
```

For context, I was using postcss-ts-classnames with tailwindcss-classnames, but for some reason, @muhammadsammy removed the possibility to import a type by name in https://github.com/muhammadsammy/tailwindcss-classnames/issues/66, and now expects the file to export a default type.

**Comment by esamattis** [comment]
Happy to accept an option like "exportAsDefault" as a pr 👍

**Comment by AdrienLemaire** [comment]
@esamattis done https://github.com/esamattis/postcss-ts-classnames/pull/8. Can we get this merged this quickly ? :heart:

**Comment by esamattis** [comment]
Closed by #8
